blank_issues_enabled: false

contact_links:
  - name: Have you read the docs?
    url: https://argo-rollouts.readthedocs.io/
    about: Much help can be found in the docs
  - name: Ask a question
    url: https://github.com/nholuongut/argo-rollouts/discussions/new
    about: Ask a question or start a discussion about Argo Rollouts
  - name: Contact on my repositories
    url: https://github.com/nholuongut/
    about: Maybe chatting with the community can help
